
/**
 * Represents the Epistemic Status of the Agent Construction Process
 */
export enum FabricationStatus {
  IDLE = 'IDLE',
  RESEARCHING = 'RESEARCHING', // New RAG Loop Step
  INGESTING = 'INGESTING', // Scraping/Reading
  DISTILLING = 'DISTILLING', // LLM Processing
  MANIFESTED = 'MANIFESTED', // Complete
  FAILED = 'FAILED' // Scars
}

export enum ViewMode {
  DASHBOARD = 'DASHBOARD',
  FORGE = 'FORGE',
  CAPSULE_LAB = 'CAPSULE_LAB',
  REGISTRY = 'REGISTRY',
  AGENTS = 'AGENTS',
  WORD_MAPPER = 'WORD_MAPPER'
}

/**
 * Core Agent Identity Structure
 */
export interface AgentIdentity {
  name: string; // The primary name of the agent
  aliases?: string[]; // Alternative names or CLI hooks
  designation: string; // e.g., "Sovereign-Class Architect"
  primeDirective: string;
  corePhilosophy: string;
}

export interface AgentTool {
  name: string;
  description: string;
  inputSchema: string; // JSON description of input
  riskLevel: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
}

export interface AgentWorkflow {
  name: string;
  trigger: string;
  steps: string[];
  outcome: string;
}

export interface AgentConstraint {
  id: string;
  type: 'HARD' | 'SOFT' | 'IMMUNE';
  description: string;
  enforcementMechanism: string;
}

export interface AgentAbility {
  name: string;
  description: string;
  dependencies: string[];
}

/**
 * Anchors represent fixed points of reference or external dependencies
 * required to ground the agent's reality.
 */
export interface AgentAnchor {
  name: string;
  description: string;
  dependencies: string[];
}

/**
 * Provenance & Security Data
 */
export interface ProvenanceDetails {
  origin: 'URL' | 'RAW_DOCUMENT' | 'RESEARCH_TOPIC';
  source: string; // URL string or "SHA-256:<hash>"
  ingestedAt: number; // Timestamp
  inputSize: number; // bytes/chars
}

export interface CryptographicSignature {
  signature: string; // Hex string
  signerPublicKey: string; // PEM or JWK exported string
  algorithm: string; // "ECDSA-P256-SHA256"
  signedAt: number;
}

export interface ProvenanceData {
  details: ProvenanceDetails;
  signature?: CryptographicSignature;
}

/**
 * The Complete Manifest generated by the Cognitive Engine
 */
export interface SovereignAgentManifest {
  identity: AgentIdentity;
  tools: AgentTool[];
  workflows: AgentWorkflow[];
  abilities: AgentAbility[];
  anchors: AgentAnchor[];
  constraints: AgentConstraint[];
  architecturalNotes: string;
  provenance?: ProvenanceData; // Optional during generation, Required after signing
}

/**
 * Version History Wrapper
 */
export interface ManifestVersion {
  id: string;
  manifest: SovereignAgentManifest;
  timestamp: number;
  inputContext: string; // Storing the original input for context
  label: string;
  sourceType?: 'FABRICATED' | 'RESTORED' | 'REFINED';
}

/**
 * UI/Error Types
 */
export interface ScarEntry {
  timestamp: number;
  code: string;
  message: string;
  context?: string;
}

/**
 * Chat Types
 */
export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  timestamp: number;
}

/**
 * Vault Identity Types
 */
export interface VaultMetadata {
  commanderName: string;
  designation: string;
  lastSync: number;
  version: string;
  commanderPublicKey?: string;
}

export interface ContentAnalysis {
  wordCount: number;
  sentiment: 'POSITIVE' | 'NEUTRAL' | 'NEGATIVE' | 'COMPLEX';
  topics: string[];
}

export interface ProvenanceIndexEntry {
  hash: string;
  agentName: string;
  timestamp: number;
  sourceType: 'RAW_DOCUMENT' | 'URL' | 'RESEARCH_TOPIC';
  snippet?: string; // First 100 chars for identification
  analysis?: ContentAnalysis;
}

export interface SovereignVault {
  metadata: VaultMetadata;
  agents: SovereignAgentManifest[];
  provenanceIndex: ProvenanceIndexEntry[];
}

// --- Context Capsule Types ---

export interface CapsuleMeta {
  id: string;
  title: string;
  primary_pill: string;
  short_tagline: string;
  tags: string[];
  worldview_ref: string | null;
  source_papers: string[];
  status: 'draft' | 'published';
  hero_cta_label: string;
  hero_cta_target: string;
}

export interface CapsuleSummaryCard {
  label: string;
  title: string;
  body: string;
  tags: string[];
}

export interface CapsuleOverview {
  id: string;
  title: string;
  hero_pills: string[];
  intro: string;
  summary_card: CapsuleSummaryCard;
}

export interface CapsuleCard {
  title: string;
  body: string;
  source_refs?: string[];
}

export interface CapsuleKeyConcepts {
  id: string;
  title: string;
  intro: string;
  cards: CapsuleCard[];
}

export interface CapsuleTable {
  columns: string[];
  rows: { cells: string[] }[];
}

export interface CapsuleStructure {
  id: string;
  title: string;
  variant: string;
  intro: string;
  table: CapsuleTable;
}

export interface CapsulePersonas {
  id: string;
  title: string;
  intro: string;
  table: CapsuleTable;
}

export interface CapsuleStep {
  id: string;
  label: string;
  summary: string;
  bullets: string[];
}

export interface CapsuleWorkflow {
  id: string;
  title: string;
  intro: string;
  steps: CapsuleStep[];
}

export interface CapsuleFailureMode {
  name: string;
  description: string;
  mitigations: string[];
}

export interface CapsuleResilience {
  id: string;
  title: string;
  intro: string;
  failure_modes: CapsuleFailureMode[];
}

export interface CapsuleMetric {
  name: string;
  description: string;
  signals: string[];
}

export interface CapsuleMetrics {
  id: string;
  title: string;
  intro: string;
  items: CapsuleMetric[];
}

export interface CapsuleChecklistItem {
  label: string;
  bullets: string[];
}

export interface CapsuleChecklist {
  id: string;
  title: string;
  intro: string;
  items: CapsuleChecklistItem[];
}

export interface ContextCapsule {
  meta: CapsuleMeta;
  sections: {
    overview?: CapsuleOverview;
    key_concepts?: CapsuleKeyConcepts;
    structure?: CapsuleStructure;
    personas?: CapsulePersonas;
    workflow?: CapsuleWorkflow;
    resilience?: CapsuleResilience;
    metrics?: CapsuleMetrics;
    checklist?: CapsuleChecklist;
  };
}